[theme]
base                     = "light"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FE"
primaryColor             = "#1A56DB"
textColor                = "#0D1117"
font                     = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true